# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'demo.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QWidget)
import q_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1497, 953)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 1440, 810))
        font = QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet(u"border-image: url(:/images/E:/\u7167\u7247/\u7eb3\u897f\u59b2.jpg);\n"
"border-radius:30px")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 90, 1440, 810))
        self.label_2.setStyleSheet(u"background-color: rgba(255, 255, 255, 245);\n"
"border-radius:30px")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1350, 100, 91, 91))
        font1 = QFont()
        font1.setPointSize(50)
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"background-color: rgba(197, 0, 0,100);\n"
"border-radius:25px\n"
"")
        self.res = QLabel(self.centralwidget)
        self.res.setObjectName(u"res")
        self.res.setGeometry(QRect(100, 730, 331, 111))
        font2 = QFont()
        font2.setPointSize(21)
        self.res.setFont(font2)
        self.res.setStyleSheet(u"background-color: rgb(255, 170, 127);\n"
"border-radius:20px")
        self.res.setTextFormat(Qt.AutoText)
        self.res.setAlignment(Qt.AlignCenter)
        self.Secondnum = QLineEdit(self.centralwidget)
        self.Secondnum.setObjectName(u"Secondnum")
        self.Secondnum.setGeometry(QRect(50, 290, 421, 71))
        font3 = QFont()
        font3.setPointSize(11)
        self.Secondnum.setFont(font3)
        self.Secondnum.setStyleSheet(u"background-color: rgb(203, 203, 203);\n"
"border-radius:30px;")
        self.Firstnum = QLineEdit(self.centralwidget)
        self.Firstnum.setObjectName(u"Firstnum")
        self.Firstnum.setGeometry(QRect(50, 200, 421, 71))
        font4 = QFont()
        font4.setPointSize(12)
        self.Firstnum.setFont(font4)
        self.Firstnum.setStyleSheet(u"background-color: rgb(203, 203, 203);\n"
"border-radius:30px;")
        self.Countbuttons = QPushButton(self.centralwidget)
        self.Countbuttons.setObjectName(u"Countbuttons")
        self.Countbuttons.setGeometry(QRect(150, 610, 231, 81))
        font5 = QFont()
        font5.setPointSize(22)
        self.Countbuttons.setFont(font5)
        self.Countbuttons.setStyleSheet(u"Countbuttons{\n"
"background-color: rgba(255, 255, 255,220);\n"
"border-radius:30px;\n"
"}\n"
"Countbuttons:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(75, 204, 191, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:30px;\n"
"}")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 130, 461, 741))
        self.label_3.setStyleSheet(u"background-color: rgba(229, 255, 231, 240);\n"
"border-radius:30px")
        self.BinA = QLabel(self.centralwidget)
        self.BinA.setObjectName(u"BinA")
        self.BinA.setGeometry(QRect(530, 670, 424, 51))
        font6 = QFont()
        font6.setPointSize(15)
        font6.setKerning(False)
        self.BinA.setFont(font6)
        self.BinA.setStyleSheet(u"background-color: rgb(221, 252, 255);")
        self.BinA.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.BinB = QLabel(self.centralwidget)
        self.BinB.setObjectName(u"BinB")
        self.BinB.setGeometry(QRect(530, 730, 424, 51))
        self.BinB.setFont(font6)
        self.BinB.setStyleSheet(u"background-color: rgb(221, 252, 255);")
        self.BinB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Binres = QLabel(self.centralwidget)
        self.Binres.setObjectName(u"Binres")
        self.Binres.setGeometry(QRect(530, 790, 424, 51))
        self.Binres.setFont(font6)
        self.Binres.setStyleSheet(u"background-color: rgb(221, 252, 255);")
        self.Binres.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Record = QTableWidget(self.centralwidget)
        if (self.Record.columnCount() < 5):
            self.Record.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.Record.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.Record.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.Record.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.Record.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.Record.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        if (self.Record.rowCount() < 1):
            self.Record.setRowCount(1)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.Record.setVerticalHeaderItem(0, __qtablewidgetitem5)
        self.Record.setObjectName(u"Record")
        self.Record.setGeometry(QRect(990, 560, 431, 321))
        self.Record.setSizeIncrement(QSize(0, 0))
        self.Record.setBaseSize(QSize(0, 0))
        self.Record.setFont(font3)
        self.Record.setLineWidth(1)
        self.Record.horizontalHeader().setVisible(True)
        self.Record.horizontalHeader().setCascadingSectionResizes(True)
        self.Record.horizontalHeader().setDefaultSectionSize(84)
        self.Record.horizontalHeader().setHighlightSections(True)
        self.Record.horizontalHeader().setStretchLastSection(True)
        self.ptr = QLabel(self.centralwidget)
        self.ptr.setObjectName(u"ptr")
        self.ptr.setGeometry(QRect(530, 600, 424, 51))
        font7 = QFont()
        font7.setFamilies([u"Microsoft YaHei UI"])
        font7.setPointSize(15)
        font7.setKerning(False)
        self.ptr.setFont(font7)
        self.ptr.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ptr.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Adder = QLabel(self.centralwidget)
        self.Adder.setObjectName(u"Adder")
        self.Adder.setGeometry(QRect(550, 140, 861, 441))
        self.Adder.setStyleSheet(u"border-image: url(:/images/F:/\u7d20\u6750/\u56fe\u7247/\u5168\u52a0\u5668.png);")
        self.StandA1 = QLabel(self.centralwidget)
        self.StandA1.setObjectName(u"StandA1")
        self.StandA1.setGeometry(QRect(550, 140, 601, 441))
        self.StandA1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4dA\u4e3a1.png);")
        self.StandA0 = QLabel(self.centralwidget)
        self.StandA0.setObjectName(u"StandA0")
        self.StandA0.setGeometry(QRect(550, 140, 601, 441))
        self.StandA0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4dA\u4e3a0.png);")
        self.StandB1 = QLabel(self.centralwidget)
        self.StandB1.setObjectName(u"StandB1")
        self.StandB1.setGeometry(QRect(550, 140, 601, 441))
        self.StandB1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4dB\u4e3a1.png);")
        self.StandB0 = QLabel(self.centralwidget)
        self.StandB0.setObjectName(u"StandB0")
        self.StandB0.setGeometry(QRect(550, 140, 601, 441))
        self.StandB0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4dB\u4e3a0.png);")
        self.Carry1 = QLabel(self.centralwidget)
        self.Carry1.setObjectName(u"Carry1")
        self.Carry1.setGeometry(QRect(550, 140, 861, 441))
        self.Carry1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u4e3a1.png);")
        self.Carry0 = QLabel(self.centralwidget)
        self.Carry0.setObjectName(u"Carry0")
        self.Carry0.setGeometry(QRect(550, 140, 861, 441))
        self.Carry0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u4e3a0.png);")
        self.Standxor1 = QLabel(self.centralwidget)
        self.Standxor1.setObjectName(u"Standxor1")
        self.Standxor1.setGeometry(QRect(550, 140, 601, 441))
        self.Standxor1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4d\u5f02\u6216\u4e3a1.png);")
        self.Standxor0 = QLabel(self.centralwidget)
        self.Standxor0.setObjectName(u"Standxor0")
        self.Standxor0.setGeometry(QRect(550, 140, 601, 441))
        self.Standxor0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4d\u5f02\u6216\u4e3a0.png);")
        self.Standout1 = QLabel(self.centralwidget)
        self.Standout1.setObjectName(u"Standout1")
        self.Standout1.setGeometry(QRect(550, 140, 601, 441))
        self.Standout1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4d\u7ed3\u679c\u4e3a1.png);")
        self.Standout0 = QLabel(self.centralwidget)
        self.Standout0.setObjectName(u"Standout0")
        self.Standout0.setGeometry(QRect(550, 140, 601, 441))
        self.Standout0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u672c\u4f4d\u7ed3\u679c\u4e3a0.png);")
        self.Carryup1 = QLabel(self.centralwidget)
        self.Carryup1.setObjectName(u"Carryup1")
        self.Carryup1.setGeometry(QRect(550, 140, 861, 441))
        self.Carryup1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u524d\u503cA\u4e3a1.png);")
        self.Carryup0 = QLabel(self.centralwidget)
        self.Carryup0.setObjectName(u"Carryup0")
        self.Carryup0.setGeometry(QRect(550, 140, 861, 441))
        self.Carryup0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u524d\u503cA\u4e3a0.png);")
        self.Carrydown1 = QLabel(self.centralwidget)
        self.Carrydown1.setObjectName(u"Carrydown1")
        self.Carrydown1.setGeometry(QRect(550, 140, 861, 441))
        self.Carrydown1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u524d\u503cB\u4e3a1.png);")
        self.Carrydown0 = QLabel(self.centralwidget)
        self.Carrydown0.setObjectName(u"Carrydown0")
        self.Carrydown0.setGeometry(QRect(550, 140, 861, 441))
        self.Carrydown0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4d\u524d\u503cB\u4e3a0.png);")
        self.Carryout1 = QLabel(self.centralwidget)
        self.Carryout1.setObjectName(u"Carryout1")
        self.Carryout1.setGeometry(QRect(550, 140, 861, 441))
        self.Carryout1.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4dOUT\u4e3a1.png);")
        self.Carryout0 = QLabel(self.centralwidget)
        self.Carryout0.setObjectName(u"Carryout0")
        self.Carryout0.setGeometry(QRect(550, 140, 861, 441))
        self.Carryout0.setStyleSheet(u"border-image: url(:/arr/\u5168\u52a0\u5668/\u8fdb\u4f4dOUT\u4e3a0.png);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 100, 291, 31))
        font8 = QFont()
        font8.setPointSize(20)
        self.label_4.setFont(font8)
        self.NumstandA = QLabel(self.centralwidget)
        self.NumstandA.setObjectName(u"NumstandA")
        self.NumstandA.setGeometry(QRect(670, 140, 71, 81))
        font9 = QFont()
        font9.setPointSize(40)
        self.NumstandA.setFont(font9)
        self.NumstandB = QLabel(self.centralwidget)
        self.NumstandB.setObjectName(u"NumstandB")
        self.NumstandB.setGeometry(QRect(670, 190, 71, 101))
        self.NumstandB.setFont(font9)
        self.Numcarry = QLabel(self.centralwidget)
        self.Numcarry.setObjectName(u"Numcarry")
        self.Numcarry.setGeometry(QRect(670, 270, 81, 91))
        self.Numcarry.setFont(font9)
        self.Numstandout = QLabel(self.centralwidget)
        self.Numstandout.setObjectName(u"Numstandout")
        self.Numstandout.setGeometry(QRect(1250, 190, 81, 101))
        self.Numstandout.setFont(font9)
        self.Numcarryout = QLabel(self.centralwidget)
        self.Numcarryout.setObjectName(u"Numcarryout")
        self.Numcarryout.setGeometry(QRect(1250, 390, 91, 111))
        self.Numcarryout.setFont(font9)
        self.Sleeptime = QDoubleSpinBox(self.centralwidget)
        self.Sleeptime.setObjectName(u"Sleeptime")
        self.Sleeptime.setGeometry(QRect(270, 420, 191, 61))
        font10 = QFont()
        font10.setPointSize(19)
        self.Sleeptime.setFont(font10)
        self.ChangeSleep = QPushButton(self.centralwidget)
        self.ChangeSleep.setObjectName(u"ChangeSleep")
        self.ChangeSleep.setGeometry(QRect(180, 520, 161, 61))
        self.ChangeSleep.setFont(font8)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 420, 171, 61))
        font11 = QFont()
        font11.setPointSize(24)
        self.label_5.setFont(font11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Firstnum.raise_()
        self.Countbuttons.raise_()
        self.Secondnum.raise_()
        self.res.raise_()
        self.BinA.raise_()
        self.BinB.raise_()
        self.Binres.raise_()
        self.Record.raise_()
        self.ptr.raise_()
        self.Adder.raise_()
        self.StandA1.raise_()
        self.pushButton.raise_()
        self.StandA0.raise_()
        self.StandB1.raise_()
        self.StandB0.raise_()
        self.Carry1.raise_()
        self.Carry0.raise_()
        self.Standxor1.raise_()
        self.Standxor0.raise_()
        self.Standout1.raise_()
        self.Standout0.raise_()
        self.Carryup1.raise_()
        self.Carryup0.raise_()
        self.Carrydown1.raise_()
        self.Carrydown0.raise_()
        self.Carryout1.raise_()
        self.Carryout0.raise_()
        self.label_4.raise_()
        self.NumstandA.raise_()
        self.NumstandB.raise_()
        self.Numcarry.raise_()
        self.Numstandout.raise_()
        self.Numcarryout.raise_()
        self.Sleeptime.raise_()
        self.ChangeSleep.raise_()
        self.label_5.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4e0e\u6216\u975e\u52a0\u6cd5\u5668", None))
        self.label.setText("")
        self.label_2.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.res.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u7ed3\u679c", None))
        self.Secondnum.setText("")
        self.Secondnum.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u4e00\u4e2a\u5927\u4e8e\u7b49\u4e8e0\u7684\u6574\u6570", None))
        self.Firstnum.setText("")
        self.Firstnum.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u4e00\u4e2a\u5927\u4e8e\u7b49\u4e8e0\u7684\u6574\u6570", None))
        self.Countbuttons.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u8ba1\u7b97", None))
        self.label_3.setText("")
        self.BinA.setText(QCoreApplication.translate("MainWindow", u"\u7b2c\u4e00\u4e2a\u6570\u7684\u4e8c\u8fdb\u5236", None))
        self.BinB.setText(QCoreApplication.translate("MainWindow", u"\u7b2c\u4e8c\u4e2a\u6570\u7684\u4e8c\u8fdb\u5236", None))
        self.Binres.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u7684\u4e8c\u8fdb\u5236", None))
        ___qtablewidgetitem = self.Record.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u672c\u4f4dA", None));
        ___qtablewidgetitem1 = self.Record.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u672c\u4f4dB", None));
        ___qtablewidgetitem2 = self.Record.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u4f4din", None));
        ___qtablewidgetitem3 = self.Record.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"\u672c\u4f4dout", None));
        ___qtablewidgetitem4 = self.Record.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u4f4dout", None));
#if QT_CONFIG(accessibility)
        self.Record.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.ptr.setText("")
        self.Adder.setText("")
        self.StandA1.setText("")
        self.StandA0.setText("")
        self.StandB1.setText("")
        self.StandB0.setText("")
        self.Carry1.setText("")
        self.Carry0.setText("")
        self.Standxor1.setText("")
        self.Standxor0.setText("")
        self.Standout1.setText("")
        self.Standout0.setText("")
        self.Carryup1.setText("")
        self.Carryup0.setText("")
        self.Carrydown1.setText("")
        self.Carrydown0.setText("")
        self.Carryout1.setText("")
        self.Carryout0.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u4e0e\u6216\u975e\u5168\u52a0\u5668", None))
        self.NumstandA.setText("")
        self.NumstandB.setText("")
        self.Numcarry.setText("")
        self.Numstandout.setText("")
        self.Numcarryout.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.ChangeSleep.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u6539\u5ef6\u65f6", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u5ef6\u65f6\u6548\u679c\uff1a", None))
    # retranslateUi

